<?php
		/*
	 * add default Bootstrap formatting to the form object
	 * and prepare() for the view
	 */
	$form = $this->addBootstrapFormAttributes($this->form)->prepare();
	$form->setAttribute('action', $this->url('acl/user/authenticate'));

	$defaultInputColumnWidth = 3;

?>
<div class="row">
	<div class="page-header">
		<h1>User Sign In</h1>
	</div>
</div>

<div class="row">

	<div class="col-md-1">
		<span class="glyphicon glyphicon-log-in" style="text-align:center; font-size:100px;"></span>
	</div>

	<div class="col-md-11">
		<?php echo $this->form()->openTag($form); ?>

		<!-- IDENTITY INPUT  -->
		<div class="form-group">
			<?php echo $this->formLabel($form->get('identity')); ?>
			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<?php echo $this->formInput($form->get('identity')); ?>
			</div>
		</div>

		<!--  CREDENTIAL INPUT -->
		<div class="form-group">
			<?php echo $this->formLabel($form->get('credential')); ?>
			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<?php echo $this->formInput($form->get('credential')); ?>
			</div>
		</div>

		<!--  SUBMIT BUTTON -->
		<div class="form-group">
			<div class="<?php
				$elements = array_values($form->getElements());
				$firstElement = $elements[0];
				echo $firstElement->getLabelAttributes()['class']; ?>">&nbsp;</div>
			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<?php echo $this->formSubmit($form->get('submit')); ?>
			</div>
		</div>

		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		automaticFocusElection();
	});



	function automaticFocusElection()
	{
		/*
			add the fields you wish to bring focus to
			in order of which you would like to consider
			them for focus. this function will bring focus
			the first input ID in the list that has nothing
			entered in it already
		*/
		var inputsToFocusOn = [
			'identity',
			'credential',
		];

		for (i = 0; i < inputsToFocusOn.length; i++) {
			var id = inputsToFocusOn[i];
			var inputSelector = '#' + id;

			if ( $(inputSelector).val() == '') {
				$(inputSelector).focus();
				break;
			}
		}
	}
</script>
