<?php
	/*
	 * add default Bootstrap formatting to the form object
	 * and prepare() for the view
	 */
	$form = $this->addBootstrapFormAttributes($this->form)->prepare();

	/*
	 * custom view helper that converts the values of a select
	 * list input into url's using the $this->url() veiw helper
	 *
	 * this allows you to make this select list a form
	 * processing switcher. routes are specified in the form
	 * definition
	 */
	$this->convertRouteSelectListToUrl($form->get('uploadType'));



	$defaultHeadingColumnWidth = 2;
	$defaultInputColumnWidth = 4;

?>
<div class="row">
	<div class="page-header">
		<h1>ACL Data Imports</h1>
	</div>
</div>

<div class="row">



	<div class="col-md-10">
		<?php echo $this->form()->openTag($form); ?>

		<!--  UPLOAD TYPE SELECTOR -->
		<div class="form-group">
			<div class="col-md-<?php echo $defaultHeadingColumnWidth; ?>">
				<?php echo $this->formLabel($form->get('uploadType')); ?>
			</div>

			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<?php echo $this->formSelect($form->get('uploadType')); ?>
			</div>
		</div>

		<!--  FILE UPLOAD INPUT -->
		<div class="form-group">
			<div class="col-md-<?php echo $defaultHeadingColumnWidth; ?>">
				<?php echo $this->formLabel($form->get('uploadFile')); ?>
			</div>

			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
					<?php echo $this->formFile($form->get('uploadFile')); ?>
			</div>
		</div>

		<!--  isDefinitive OPTION CHECKBOX -->
		<div class="form-group">
			<div class="col-md-<?php echo $defaultHeadingColumnWidth; ?>">
				&nbsp;
			</div>

			<div class="col-md-<?php echo (12 - $defaultHeadingColumnWidth); ?>">
				<?php echo $this->formCheckbox($form->get('isDefinitive')); ?>
				&nbsp;
				<span style="font-weight:bold; font-size:14px;" class="isDefinitive">
					<?php echo $form->get('isDefinitive')->getLabel(); ?>
				</span>
			</div>
		</div>

		<!--  SUBMIT BUTTON -->
		<div class="form-group">
			<div class="col-md-<?php echo $defaultHeadingColumnWidth; ?>">
				&nbsp;
			</div>

			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<?php echo $this->formSubmit($form->get('submit')); ?>
			</div>
		</div>

		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<script type="text/javascript">
	var fileTypeInput = $('#<?php echo $form->get('uploadType')->getAttribute('id'); ?>');
	var filePathInput = $('#<?php echo $form->get('uploadFile')->getAttribute('id'); ?>');


	$(document).ready(function() {
		$('form').attr('action', $(fileTypeInput).val() );

		/*
			apply Bootstrap CSS styling to all file upload controls
		*/
		$('input[type="checkbox"]')
			.removeClass('form-control');

		$('input[type="file"]')
			.removeClass('form-control')
			.addClass('file');


		$(fileTypeInput).change( function() {
			$('#import').attr('action', $(fileTypeInput).val());
		});


	});



</script>
