<?php
	$form = $this->form->prepare();
	$form->setAttribute('class', 'form-horizontal');

	foreach($form->getElements() as $element) {
		/*
		 * controls how far the form indents into
		 * the page using Twitter:Bootstrap CSS
		 *
		 */
		$defLabelAttributes = array(
			'class' => 'control-label col-md-2',
		);

		/*
		 * default class for all input controls
		 * for the Twitter:Bootstrap CSS framework
		 * to apply standard styling
		 */
		$defElementClass = 'form-control';

		$element->setLabelAttributes( $defLabelAttributes);
		$element->setAttribute('class', $defElementClass);
		$element->setAttribute('id', $element->getName());
	}

	/*
	 * the submit button is a little different, it uses
	 * a button class to proper rendering
	 *
	 */
	$form->get('submit')->setAttribute('class', 'btn btn-success');


	$defaultInputColumnWidth = 3;

?>
<div class="row">
	<div class="page-header">
		<h1>ACL Imports</h1>
	</div>
</div>

<div class="row">



	<div class="col-md-10">
		<?php echo $this->form()->openTag($form); ?>

		<!--  NEW PASSWORD INPUT -->
		<div class="form-group">
			<?php echo $this->formLabel($form->get('uploadType')); ?>
			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<?php echo $this->formSelect($form->get('uploadType')); ?>
			</div>
		</div>

		<!--  CONFIRM NEW PASSWORD INPUT -->
		<div class="form-group">
			<?php echo $this->formLabel($form->get('uploadFile')); ?>
			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<!--  <div class="input-group">-->
					<?php echo $this->formFile($form->get('uploadFile')); ?>
					<!-- <span class="input-group-addon" id="confirmPasswordInputGroup"><span class="glyphicon glyphicon-pencil" id="confirmPasswordGlyphicon"></span></span> -->
				<!-- </div> -->
			</div>
		</div>

		<!--  SUBMIT BUTTON -->
		<div class="form-group">
			<div class="<?php
				$elements = array_values($form->getElements());
				$firstElement = $elements[0];
				echo $firstElement->getLabelAttributes()['class']; ?>">&nbsp;</div>
			<div class="col-md-<?php echo $defaultInputColumnWidth; ?>">
				<?php echo $this->formSubmit($form->get('submit')); ?>
			</div>
		</div>

		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<script type="text/javascript">
	var fileInput = $('#<?php echo $form->get('uploadFile')->getAttribute('id'); ?>');

	$(document).ready(function() {
		/*
			apply Bootstrap CSS styling to all file upload controls
		*/
		$('input[type="file"]')
			.removeClass('form-control')
			.addClass('file');
	});



</script>
